/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PageRouteImport } from './routes/$page'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminEmailsRouteImport } from './routes/admin/emails'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as DevEmailPreviewRouteImport } from './routes/dev/email-preview'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffActivityRouteImport } from './routes/staff/activity'
import { Route as StaffCategoriesRouteImport } from './routes/staff/categories'
import { Route as StaffCustomizationRouteImport } from './routes/staff/customization'
import { Route as StaffHealthRouteImport } from './routes/staff/health'
import { Route as StaffInventoryRouteImport } from './routes/staff/inventory'
import { Route as StaffTeamRouteImport } from './routes/staff/team'
import { Route as StaffOrdersIndexRouteImport } from './routes/staff/orders/index'
import { Route as StaffOrdersIdRouteImport } from './routes/staff/orders/$id'
import { Route as StaffProductsIndexRouteImport } from './routes/staff/products/index'
import { Route as StaffProductsIdRouteImport } from './routes/staff/products/$id'
import { Route as StaffProductsNewRouteImport } from './routes/staff/products/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/admin/emails',
  path: '/admin/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DevEmailPreviewRoute = DevEmailPreviewRouteImport.update({
  id: '/dev/email-preview',
  path: '/dev/email-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffActivityRoute = StaffActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCategoriesRoute = StaffCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCustomizationRoute = StaffCustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => StaffRoute,
} as any)
const StaffHealthRoute = StaffHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => StaffRoute,
} as any)
const StaffInventoryRoute = StaffInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTeamRoute = StaffTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => StaffRoute,
} as any)
const StaffOrdersIndexRoute = StaffOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffOrdersIdRoute = StaffOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProductsIndexRoute = StaffProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProductsIdRoute = StaffProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProductsNewRoute = StaffProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRouteWithChildren
  '/track': typeof TrackRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dev/email-preview': typeof DevEmailPreviewRoute
  '/product/$slug': typeof ProductSlugRoute
  '/staff/activity': typeof StaffActivityRoute
  '/staff/categories': typeof StaffCategoriesRoute
  '/staff/customization': typeof StaffCustomizationRoute
  '/staff/health': typeof StaffHealthRoute
  '/staff/inventory': typeof StaffInventoryRoute
  '/staff/team': typeof StaffTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/orders/$id': typeof StaffOrdersIdRoute
  '/staff/products/$id': typeof StaffProductsIdRoute
  '/staff/products/new': typeof StaffProductsNewRoute
  '/staff/orders/': typeof StaffOrdersIndexRoute
  '/staff/products/': typeof StaffProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dev/email-preview': typeof DevEmailPreviewRoute
  '/product/$slug': typeof ProductSlugRoute
  '/staff/activity': typeof StaffActivityRoute
  '/staff/categories': typeof StaffCategoriesRoute
  '/staff/customization': typeof StaffCustomizationRoute
  '/staff/health': typeof StaffHealthRoute
  '/staff/inventory': typeof StaffInventoryRoute
  '/staff/team': typeof StaffTeamRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/staff/orders/$id': typeof StaffOrdersIdRoute
  '/staff/products/$id': typeof StaffProductsIdRoute
  '/staff/products/new': typeof StaffProductsNewRoute
  '/staff/orders': typeof StaffOrdersIndexRoute
  '/staff/products': typeof StaffProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRouteWithChildren
  '/track': typeof TrackRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dev/email-preview': typeof DevEmailPreviewRoute
  '/product/$slug': typeof ProductSlugRoute
  '/staff/activity': typeof StaffActivityRoute
  '/staff/categories': typeof StaffCategoriesRoute
  '/staff/customization': typeof StaffCustomizationRoute
  '/staff/health': typeof StaffHealthRoute
  '/staff/inventory': typeof StaffInventoryRoute
  '/staff/team': typeof StaffTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/orders/$id': typeof StaffOrdersIdRoute
  '/staff/products/$id': typeof StaffProductsIdRoute
  '/staff/products/new': typeof StaffProductsNewRoute
  '/staff/orders/': typeof StaffOrdersIndexRoute
  '/staff/products/': typeof StaffProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$page'
    | '/account'
    | '/cart'
    | '/catalogue'
    | '/checkout'
    | '/confirmation'
    | '/login'
    | '/robots.txt'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/staff'
    | '/track'
    | '/admin/emails'
    | '/auth/signin'
    | '/auth/signup'
    | '/dev/email-preview'
    | '/product/$slug'
    | '/staff/activity'
    | '/staff/categories'
    | '/staff/customization'
    | '/staff/health'
    | '/staff/inventory'
    | '/staff/team'
    | '/admin/'
    | '/staff/'
    | '/staff/orders/$id'
    | '/staff/products/$id'
    | '/staff/products/new'
    | '/staff/orders/'
    | '/staff/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$page'
    | '/account'
    | '/cart'
    | '/catalogue'
    | '/checkout'
    | '/confirmation'
    | '/login'
    | '/robots.txt'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/track'
    | '/admin/emails'
    | '/auth/signin'
    | '/auth/signup'
    | '/dev/email-preview'
    | '/product/$slug'
    | '/staff/activity'
    | '/staff/categories'
    | '/staff/customization'
    | '/staff/health'
    | '/staff/inventory'
    | '/staff/team'
    | '/admin'
    | '/staff'
    | '/staff/orders/$id'
    | '/staff/products/$id'
    | '/staff/products/new'
    | '/staff/orders'
    | '/staff/products'
  id:
    | '__root__'
    | '/'
    | '/$page'
    | '/account'
    | '/cart'
    | '/catalogue'
    | '/checkout'
    | '/confirmation'
    | '/login'
    | '/robots.txt'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/staff'
    | '/track'
    | '/admin/emails'
    | '/auth/signin'
    | '/auth/signup'
    | '/dev/email-preview'
    | '/product/$slug'
    | '/staff/activity'
    | '/staff/categories'
    | '/staff/customization'
    | '/staff/health'
    | '/staff/inventory'
    | '/staff/team'
    | '/admin/'
    | '/staff/'
    | '/staff/orders/$id'
    | '/staff/products/$id'
    | '/staff/products/new'
    | '/staff/orders/'
    | '/staff/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageRoute: typeof PageRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CatalogueRoute: typeof CatalogueRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmationRoute: typeof ConfirmationRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffRoute: typeof StaffRouteWithChildren
  TrackRoute: typeof TrackRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  DevEmailPreviewRoute: typeof DevEmailPreviewRoute
  ProductSlugRoute: typeof ProductSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$page': {
      id: '/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/email-preview': {
      id: '/dev/email-preview'
      path: '/dev/email-preview'
      fullPath: '/dev/email-preview'
      preLoaderRoute: typeof DevEmailPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/activity': {
      id: '/staff/activity'
      path: '/activity'
      fullPath: '/staff/activity'
      preLoaderRoute: typeof StaffActivityRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/categories': {
      id: '/staff/categories'
      path: '/categories'
      fullPath: '/staff/categories'
      preLoaderRoute: typeof StaffCategoriesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/customization': {
      id: '/staff/customization'
      path: '/customization'
      fullPath: '/staff/customization'
      preLoaderRoute: typeof StaffCustomizationRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/health': {
      id: '/staff/health'
      path: '/health'
      fullPath: '/staff/health'
      preLoaderRoute: typeof StaffHealthRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/inventory': {
      id: '/staff/inventory'
      path: '/inventory'
      fullPath: '/staff/inventory'
      preLoaderRoute: typeof StaffInventoryRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/team': {
      id: '/staff/team'
      path: '/team'
      fullPath: '/staff/team'
      preLoaderRoute: typeof StaffTeamRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/orders/': {
      id: '/staff/orders/'
      path: '/orders'
      fullPath: '/staff/orders/'
      preLoaderRoute: typeof StaffOrdersIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/orders/$id': {
      id: '/staff/orders/$id'
      path: '/orders/$id'
      fullPath: '/staff/orders/$id'
      preLoaderRoute: typeof StaffOrdersIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/products/': {
      id: '/staff/products/'
      path: '/products'
      fullPath: '/staff/products/'
      preLoaderRoute: typeof StaffProductsIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/products/$id': {
      id: '/staff/products/$id'
      path: '/products/$id'
      fullPath: '/staff/products/$id'
      preLoaderRoute: typeof StaffProductsIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/products/new': {
      id: '/staff/products/new'
      path: '/products/new'
      fullPath: '/staff/products/new'
      preLoaderRoute: typeof StaffProductsNewRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface StaffRouteChildren {
  StaffActivityRoute: typeof StaffActivityRoute
  StaffCategoriesRoute: typeof StaffCategoriesRoute
  StaffCustomizationRoute: typeof StaffCustomizationRoute
  StaffHealthRoute: typeof StaffHealthRoute
  StaffInventoryRoute: typeof StaffInventoryRoute
  StaffTeamRoute: typeof StaffTeamRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffOrdersIdRoute: typeof StaffOrdersIdRoute
  StaffProductsIdRoute: typeof StaffProductsIdRoute
  StaffProductsNewRoute: typeof StaffProductsNewRoute
  StaffOrdersIndexRoute: typeof StaffOrdersIndexRoute
  StaffProductsIndexRoute: typeof StaffProductsIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffActivityRoute: StaffActivityRoute,
  StaffCategoriesRoute: StaffCategoriesRoute,
  StaffCustomizationRoute: StaffCustomizationRoute,
  StaffHealthRoute: StaffHealthRoute,
  StaffInventoryRoute: StaffInventoryRoute,
  StaffTeamRoute: StaffTeamRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffOrdersIdRoute: StaffOrdersIdRoute,
  StaffProductsIdRoute: StaffProductsIdRoute,
  StaffProductsNewRoute: StaffProductsNewRoute,
  StaffOrdersIndexRoute: StaffOrdersIndexRoute,
  StaffProductsIndexRoute: StaffProductsIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageRoute: PageRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CatalogueRoute: CatalogueRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmationRoute: ConfirmationRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffRoute: StaffRouteWithChildren,
  TrackRoute: TrackRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  DevEmailPreviewRoute: DevEmailPreviewRoute,
  ProductSlugRoute: ProductSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
